final_project/models/__init__.py
__all__ = (
    "db",
    "Video",
)

from .database import db
from .video import Video

final_project/models/database.py
__all__ = ("db",)

from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

final_project/models/video.py
from typing import TYPE_CHECKING

from sqlalchemy import Column, Integer, String

from .database import db

if TYPE_CHECKING:
    from flask_sqlalchemy.query import Query


class Video(db.Model):
    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    link = Column(String, nullable=False)
    watch = Column(String, nullable=False)

    if TYPE_CHECKING:
        query: Query

final_project/views/forms/videos.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired, Length


class VideoForm(FlaskForm):
    name = StringField(
        label="Название видео",
        validators=[
            DataRequired(),
            Length(min=3),
        ],
    )
    link = StringField(
        label="Ссылка на YouTube",
        validators=[
            DataRequired(),
            Length(min=3),
        ],
    )

final_project/app.py
from os import getenv, path

from flask import Flask
from flask import request
from flask import render_template
from flask import flash
from flask import redirect
from flask import url_for
from flask import send_from_directory

from flask_migrate import Migrate
from flask_wtf.csrf import CSRFProtect

from models import db
from views.videos import videos_app

from models import db, Video

app = Flask(__name__)
app.register_blueprint(videos_app)

config_class_name = getenv("CONFIG_CLASS", "DevelopmentConfig")
config_object = f"config.{config_class_name}"
app.config.from_object(config_object)

db.init_app(app)
migrate = Migrate(app=app, db=db)
csrf = CSRFProtect(app)

@app.get("/", endpoint="index")
def hello_root():
    videos: list[Video] = Video.query.order_by(Video.id).all()
    return render_template("index.html", videos=videos)

@app.route('/upload/<name>')
def download(name):
    return send_from_directory(path.join(app.root_path, 'upload'), name)

final_project/main.py
__all__ = ("app",)

from app import app

final_project/views/videos.py
import os

from flask import request
from flask import redirect
from flask import url_for
from flask import Blueprint
from flask import render_template
from flask import flash
from flask import current_app

from models import db, Video
from werkzeug.utils import secure_filename

from .forms.videos import VideoForm

videos_app = Blueprint(
    "videos_app",
    __name__,
    url_prefix="/videos",
)


@videos_app.get("/", endpoint="list")
def get_videos_list():
    videos: list[Video] = Video.query.order_by(Video.id).all()
    return render_template("index.html", videos=videos)


def get_video_by_id(video_id: int) -> Video:
    return Video.query.get_or_404(
        video_id,
        description=f"Video #{video_id} not found!",
    )


@videos_app.get("/<int:video_id>/", endpoint="details")
def get_video_details(video_id: int):
    video = get_video_by_id(video_id=video_id)
    return render_template("videos/details.html", video=video)


@videos_app.route("/add/", methods=["GET", "POST"], endpoint="add")
def create_new_video():
    form = VideoForm()
    if request.method == "GET":
        return render_template("videos/add.html", form=form)

    if not form.validate_on_submit():
        return render_template("videos/add.html", form=form), 400

    watch = form.data["link"].split("=")[1]
    video = Video(name=form.data["name"], link=form.data["link"], watch=watch)
    db.session.add(video)
    db.session.commit()
    url = url_for("videos_app.details", video_id=video.id)
    flash(f"Created video {video.name!r}", category="primary")
    return redirect(url)


@videos_app.route("/upload/", methods=["GET", "POST"], endpoint="upload")
def upload_new_video():
    form = VideoForm()
    return render_template("videos/upload.html", form=form.name)


@videos_app.route(
    "/<int:video_id>/confirm-delete/",
    methods=["GET", "POST"],
    endpoint="confirm-delete",
)
def confirm_delete_video(video_id: int):
    video = get_video_by_id(video_id=video_id)
    if request.method == "GET":
        return render_template("videos/confirm-delete.html", video=video)

    video_name = video.name
    db.session.delete(video)
    db.session.commit()
    flash(f"Deleted video {video_name!r}", category="warning")
    url = url_for("videos_app.list")
    return redirect(url)


@videos_app.route('/success/', methods=['POST'], endpoint="success")
def success():
    if request.method == 'POST':
        f = request.files['file']
        filename = secure_filename(f.filename)
        fullpath = os.path.join(current_app.root_path, 'upload', filename)
        videopath = os.path.join('/upload', filename)
        f.save(fullpath)
        video = Video(name=request.form['name'], link=videopath, watch="-")
        db.session.add(video)
        db.session.commit()
        return render_template("videos/success.html", name=request.form['name'])

final_project/templates/base.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AppTube - {% block title %}Title{% endblock %}</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    {% block head %}
    {% endblock %}

</head>

<body>

<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Тема</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Светлая
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Тёмная
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                Авто
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>


<header data-bs-theme="dark">
    <div class="collapse text-bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4>AppTube</h4>
                    <p class="text-body-secondary">
                        Приложение AppTube - бесплатный видеохостинг для всех желающих!
                    </p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4>Меню</h4>
                    <ul class="list-unstyled">
                        <li><a href="{{ url_for('index') }}" class="text-white">Главная</a></li>
                        <li><a href="{{ url_for('videos_app.add') }}" class="text-white">Добавить видео из YouTube</a></li>
                        <li><a href="{{ url_for('videos_app.upload') }}" class="text-white">Загрузить своё видео</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a href="{{ url_for('index') }}" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                     stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                     viewBox="0 0 24 24">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                    <circle cx="12" cy="13" r="4"/>
                </svg>
                <strong>AppTube</strong>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main>

    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            {% block body %}
            Base body
            {% endblock %}
        </div>
    </div>

</main>

<footer class="text-body-secondary py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">К началу страницы</a>
        </p>
        <p class="mb-1">AppTube &copy; Дмитрий Новожилов, 2023</p>
    </div>
</footer>
<script src="/docs/5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>


<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/color-modes.js') }}"></script>
</body>
</html>

final_project/templates/index.html
{% extends 'base.html' %}

{% block title %}
  Видеохостинг для всех!
{% endblock %}

{% from 'macros/show-flashed-messages.html' import show_flashed_messages_with_categories %}

{% block body %}
  {{ show_flashed_messages_with_categories() }}

  {% if videos %}
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      {% for video in videos %}
      <div class="col">
          <div class="card shadow-sm">
            <a href="{{ url_for('videos_app.details', video_id=video.id) }}">
              {% if video.watch == "-" %}
                <img class="img-fluid" src="https://idei.club/raznoe/uploads/posts/2023-05/1685543289_idei-club-p-svetoch-mebel-krasivo-60.jpg">
              {% else %}
                <img class="img-fluid" src="//i3.ytimg.com/vi/{{ video.watch }}/maxresdefault.jpg">
              {% endif %}
            </a>
            <div class="card-body">
              <p class="card-text">{{ video.name }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{{ url_for('videos_app.details', video_id=video.id) }}" class="btn btn-sm btn-outline-secondary">Подробно</a>
                  <a href="{{ url_for('videos_app.confirm-delete', video_id=video.id) }}" class="btn btn-sm btn-outline-secondary">Удалить</a>
                </div>
              </div>
            </div>
          </div>
        </div>

      {% endfor %}
    </div>
  {% else %}
    <div class="alert alert-warning" role="alert">
      Пока не загружено ни одного видео :(
      <br><br>
      <a href="{{ url_for('videos_app.add') }}">Станьте первым!</a>
    </div>
  {% endif %}
{% endblock %}

final_project/templates/macros/show-flashed-messages.html
{% macro show_flashed_messages_with_categories(default_category="primary") %}
  {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="my-2 alert alert-
        {%- if category == 'message' -%}
          {{ default_category }}
        {%- else -%}
          {{ category }}
        {%- endif -%}
">{{ message }}</div>
      {% endfor %}
    {% endif %}
  {% endwith %}
{% endmacro %}

final_project/templates/videos/add.html
{% extends 'base.html' %}

{% block title %}
  Добавить видео с YouTube
{% endblock %}

{% block body %}
  <h3>Добавить видео с YouTube</h3>
  <div>
    <form method="post">

      <div class="my-3">

        {{ form.hidden_tag() }}
        {{ form.name.label(class="form-label") }}
        {{ form.name(size=20, class="form-control") }}

        {% if form.errors %}
          {% for field_name, errors in form.errors.items() %}
            <div class="my-3 alert alert-danger">
              <strong>{{ field_name }}</strong>
              <ul>
                {% for error in errors %}
                  <li>{{ error }}</li>
                {% endfor %}
              </ul>
            </div>
          {% endfor %}
        {% endif %}

      </div>

      <div class="my-3">

        {{ form.hidden_tag() }}
        {{ form.link.label(class="form-label") }}
        {{ form.link(size=20, class="form-control") }}

        {% if form.errors %}
          {% for field_name, errors in form.errors.items() %}
            <div class="my-3 alert alert-danger">
              <strong>{{ field_name }}</strong>
              <ul>
                {% for error in errors %}
                  <li>{{ error }}</li>
                {% endfor %}
              </ul>
            </div>
          {% endfor %}
        {% endif %}

      </div>

      <input class="btn btn-primary" type="submit" value="Добавить">
    </form>
  </div>
  <div class="mt-5">
    <a href="{{ url_for('videos_app.list') }}">
      К списку видео
    </a>
  </div>
{% endblock %}

final_project/templates/videos/confirm-delete.html
{% extends 'base.html' %}

{% block title %}
  Удаление видео - {{ video.name }}
{% endblock %}

{% block body %}
  <h3>Вы уверены, что хотите удалить видео <code>&quot;{{ video.name }}&quot;</code>?</h3>
  <h4>Это действие необратимо!</h4>

  <div class="mt-4">
    <form method="post">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
      <input class="btn btn-danger" type="submit" value="Удалить">
    </form>
  </div>

  <div class="mt-5">
    <a href="{{ url_for('videos_app.list') }}">
      К списку видео
    </a>
  </div>
{% endblock %}

final_project/templates/videos/details.html
{% extends 'base.html' %}

{% block title %}
  {{ video.name }}
{% endblock %}

{% from 'macros/show-flashed-messages.html' import show_flashed_messages_with_categories %}

{% block body %}
  {{ show_flashed_messages_with_categories("dark") }}

  <h3>{{ video.name }}</h3>
  {% if video.watch == "-" %}
    <video controls width="100%">
      <source src="{{ video.link }}" type="video/mp4">
    </video>
  {% else %}
    <iframe width="100%"
            height="700"
            class="mt-4"
            src="https://www.youtube.com/embed/{{video.watch}}"
            title="YouTube video player"
            frameborder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
            allowfullscreen>
    </iframe>
  {% endif %}
  <div class="mt-5">
    <a href="{{ url_for('videos_app.list') }}">
      К списку видео
    </a>
  </div>
{% endblock %}

final_project/templates/videos/go.html
{% extends 'base.html' %}

{% block title %}
  Go video #{{ video.id }}
{% endblock %}

{% from 'macros/show-flashed-messages.html' import show_flashed_messages_with_categories %}

{% block body %}
  {{ show_flashed_messages_with_categories("dark") }}

  <h3>Video {{ video.name }}</h3>
  <iframe width="1500" 
          height="700"
          src="https://www.youtube.com/embed/{{video.watch}}"
          title="YouTube video player"
          frameborder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
          allowfullscreen>
  </iframe>
  <div class="space-top">
    <a class="no-underline" href="{{ url_for('videos_app.list') }}">
      Back to video list
    </a>
  </div>
{% endblock %}

final_project/templates/videos/success.html
{% extends 'base.html' %}

{% block title %}
    success
{% endblock %}

{% block body %} 
    <div class="alert alert-success" role="alert">
        Ваше видео &quot;{{name}}&quot; успешно загружено
    </div>
  <div class="mt-5">
    <a href="{{ url_for('videos_app.list') }}">
      К списку видео
    </a>
  </div>
{% endblock %} 

final_project/templates/videos/upload.html
{% extends 'base.html' %}

{% block title %}
  Загрузить своё видео
{% endblock %}

{% block body %}
  <div>
    <form action="{{ url_for('videos_app.success') }}" method="post" enctype="multipart/form-data">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
      <div class="mb-3">
        <label for="name" class="form-label">Название видео</label>
        <input type="text" class="form-control" name="name" id="name">
      </div>
      <div class="mb-3">
        <label for="file" class="form-label">Загрузить с компьютера</label>
        <input type="file" class="form-control" name="file" id="file">
      </div>
      <div class="mb-3">
        <input class="btn btn-primary" type="submit" value="Загрузить">
      </div>
    </form>
  </div>

  <div class="mt-5">
    <a href="{{ url_for('videos_app.list') }}">
      К списку видео
    </a>
  </div>
{% endblock %}